
services:
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - "/var/lib/postgresql/data"
